services:
  backend:
    build: { context: ./backend, dockerfile: Dockerfile.dev }
    container_name: inv_backend
    restart: unless-stopped
    ports: ["5000:5000"]
    env_file: ./backend/.env
    volumes: ["./backend:/app", "/app/node_modules"]
    networks: [inv_net]

  frontend:
    build: { context: ./frontend, dockerfile: Dockerfile.dev }
    container_name: inv_frontend
    restart: unless-stopped
    ports: ["5173:5173"]
    env_file: ./frontend/.env
    volumes: ["./frontend:/app", "/app/node_modules"]
    networks: [inv_net]

networks:
  inv_net:
    driver: bridge
